### PR TITLE
added in the docker auth function to export

### PR DESCRIPTION
**Pull request by muschellij2**
Tidied up a few things with the target that were failiing R CMD check and exported the docker auth step as it is useful for some most likely.

### CODE REVIEW

**Comment by muschellij2** [comment]
I've also added the ability for `cr_deploy_docker_construct` (and therefore `cr_deploy_docker`) to pass relevant argument to `cr_build_yaml` in case you need to add options/substitutions/etc

**Comment by muschellij2** [comment]
I have run into issues with calling `docker_auth` explicitly now, so I don't think we need to do that given the new docker images from GCP builders

**Comment by muschellij2** [comment]
This should now pass all checks except for the linter and `CodeFactor` as it seems as though codefactor is reaading roxygen2 headers and failing and linter has some collation issues and some other warnings that are not real fails.

**Comment by MarkEdmondson1234** [comment]
@muschellij2 this is a super monster pull request now, I suggest we close this one, you can merge with CRAN version then we can target smaller pull requests to get them in next release.

**Comment by muschellij2** [comment]
I am relying on this for my pipelines because of the issues that arise in this PR.  What would you suggest with the splits?  We may just simply have to maintain our own branch due to the number of issues that arose.

**Comment by MarkEdmondson1234** [comment]
The best way to get the quickly merged will be:

* An issue to refer to that holds an example of what it does, why its needed etc.
* A working test for any new code
* One pull request per issue (on its own branch, perhaps use https://usethis.r-lib.org/articles/pr-functions.html to help)
* An example and documentation if necessary

**Pull request closed without merging**
